//Creado con Ardora - www.webardora.net
//bajo licencia Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
//para otros usos contacte con el autor
var timeAct=360; timeIni=360; timeBon=0;
var successes=0; successesMax=3; attempts=0; attemptsMax=1;
var score=0; scoreMax=3; scoreInc=1; scoreDec=1
var typeGame=0;
var tiTime=true;
var tiTimeType=0;
var tiButtonTime=true;
var textButtonTime="Comenzar";
var tiSuccesses=false;
var tiAttempts=false;
var tiScore=false;
var startTime;
var colorBack="#FFFFFF"; colorButton="#800000"; colorText="#000000"; colorSele="#FF8080";
var goURLNext=false; goURLRepeat=false;tiAval=false;
var scoOk=0; scoWrong=0; scoOkDo=0; scoWrongDo=0; scoMessage=""; scoPtos=10;
var fMenssage="Verdana, Geneva, sans-serif";
var fActi="Verdana, Geneva, sans-serif";
var fEnun="Verdana, Geneva, sans-serif";
var timeOnMessage=5; messageOk="Felicitaciones"; messageTime=""; messageError="Losentimos"; messageErrorG="Losentimos"; messageAttempts=""; isShowMessage=false;
var urlOk=""; urlTime=""; urlError=""; urlAttempts="";
var goURLOk="_blank"; goURLTime="_blank"; goURLAttempts="_blank"; goURLError="_blank"; 
borderOk="#008000"; borderTime="#FF0000";borderError="#FF0000"; borderAttempts="#FF0000";
var wordsGame="U2VtYW5hXzE4"; wordsStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function giveZindex(typeElement){var valueZindex=0; capas=document.getElementsByTagName(typeElement);
for (i=0;i<capas.length;i++){if (parseInt($(capas[i]).css("z-index"),10)>valueZindex){valueZindex=parseInt($(capas[i]).css("z-index"),10);}}return valueZindex;}
var actMaxWidth="600"; actMaxHeight="320";profG=0;dirMedia="Semana_18_resources/media/";
var indexG=0;
var words1G=["RWwgSW5zdGl0dXRvIGRlIEVkdWNhY2nDs24gU3VwZXJpb3IgVGVjbm9sw7NnaWNvIFDDumJsaWNvIFNhbiBJZ25hY2lvIGRlIExveW9sYSwgc2UgZW5jdWVudHJhIHViaWNhZG8gZW4gZWwgZGlzdHJpdG8sIHByb3ZpbmNpYSB5IFJlZ2nDs24gSnVuw61uLCBhIHVuYSBhbHRpdHVkIGRlIDQxMDUgbXNubS4=","RWwgMjIgZGUgZGljaWVtYnJlIGRlIDE5ODQgc2UgY29uZm9ybcOzIGVsIGNvbWl0w6kgcHJvIGNyZWFjacOzbiBkZWwgSW5zdGl0dXRvIFN1cGVyaW9yIHBhcmEgY2FuYWxpemFyIGVzdGFzIGdlc3Rpb25lcyB5IGZvcm1hbGl6YXIgZWwgZXhwZWRpZW50ZSB0w6ljbmljbyBhbnRlIGVsIE1pbmlzdGVyaW8gZGUgRWR1Y2FjacOzbiwgZXMgYXPDrSBxdWUgbGEgQ29tdW5pZGFkIENhbXBlc2luYSBkb25hIHVuIHRlcnJlbm8gcGFyYSBsYSBjb25zdHJ1Y2Npw7NuIGRlIHN1IGluZnJhZXN0cnVjdHVyYSwgY29tbyB1biBhY3RvIGRlIGZpbGFudHJvcMOtYSBwYXJhIGVsIG5vYmxlIGZpbiBkZSBsYSBlZHVjYWNpw7NuIHN1cGVyaW9yIGRlIHN1cyBoaWpvcy4=","RmluYWxtZW50ZSBlbCBjYXJvIGFuaGVsbyBzZSB2ZSBjcmlzdGFsaXphbmRvIGNvbiBsYSBSZXNvbHVjacOzbiBNaW5pc3RlcmlhbCBOwrAgMjc1LTg1IC0gRUQgZGVsIDE1IGRlIG1hcnpvIGRlIDE5ODUgY29uIGxhcyBlc3BlY2lhbGlkYWRlcyBkZSBQcm9kdWNjacOzbiBBZ3LDrWNvbGEgeSBDb250YWJpbGlkYWQu","RGVzcHXDqXMgZGUgYWdvdGFkb3JhcyBnZXN0aW9uZXMgc2UgbG9ncmEgdW5hIHBhcnRpZGEgcHJlc3VwdWVzdGFsIHBhcmEgZWwgZnVuY2lvbmFtaWVudG8geSBhcGVydHVyYSBkZSBsYSBJbnN0aXR1Y2nDs24gZWwgNCBkZSBub3ZpZW1icmUgZGUgMTk4NSwgZWwgTG9jYWwgcXVlIG90b3JnYSBlbiBzZXNpw7NuIGRlIHVzbyBsYSBNdW5pY2lwYWxpZGFkIFByb3ZpbmNpYWwgZGUgSnVuw61uIHViaWNhZGEgZW4gbGEgQ3VhZHJhLiA4IGRlbCBKci4gU2ltw7NuIEJvbMOtdmFyIChFeCBsb2NhbCBkZWwgUHVlc3RvIGRlIFNhbHVkKS4gU2llbmRvIHN1IHByaW1lciBEaXJlY3RvciBQcm9mLiBEZWxmw61uIEJhbGRlw7NuIFJpY2FsZGkuIFBvc3Rlcmlvcm1lbnRlIHNlIGNyZWEgbGEgZXNwZWNpYWxpZGFkIGRlIEVuZmVybWVyw61hIGNvbiBSLkQuIE7CsCA4MTYtODktRUQu","RGUgc3VzIGF1bGFzIHNlIGZvcmphcm9uIGdyYW5kZXMgeSBleGl0b3NvcyBwcm9mZXNpb25hbGVzIHF1ZSBhY3R1YWxtZW50ZSBsYWJvcmFuIGVuIGRpZmVyZW50ZXMgaW5zdGl0dWNpb25lcyBww7pibGljYXMgeSBwcml2YWRhcyBkZSBsYSBSZWdpw7NuIHkgZGVsIGV4dHJhbmplcm8uIENvbiBlbCB0cmFuc2N1cnJpciBkZSBsb3MgYcOxb3MgeSBsYXMgY2lyY3Vuc3RhbmNpYXMgb2JsaWdhbiBhIGxhIGluc3RpdHVjacOzbiBhIGxhIGNyZWFjacOzbiBkZSBvdHJhcyBlc3BlY2lhbGlkYWRlcywgZXMgYXPDrSBxdWUgc2UgY3JlYSBsYSBlc3BlY2lhbGlkYWQgZGUgQ29tcHV0YWNpw7NuIGUgSW5mb3Jtw6F0aWNhIGNvbiBSLkQuIE7CsCAwMDg5LTk3LUVEIHkgU2VjcmV0YXJpYWRvIEVqZWN1dGl2byBjb24gUi5ELiBOwrAgMjIzLTk5LUVELg=="];
var words2G=["wr9RdcOpIHNvbiBsYXMgZXN0cnVjdHVyYXMgZGUgZGF0b3M/","UGVuc2Vtb3MgZW4gYWxndW5hcyBjb3NhcyBkZWwgZMOtYSBhIGTDrWEuIFNpZW1wcmUgdGVuZW1vcyBuZWNlc2lkYWRlcyBiw6FzaWNhcywgY29tbyBhZ3J1cGFyIGxhcyBjb3Nhcy4gUG9yIGVqZW1wbG8gZWwgYXJtYXJpbyBkZSB0dSBjYXNhLCBkb25kZSB0aWVuZXMgdW4gY29uanVudG8gZGUgY2FtaXNldGFzLCBubyBsYXMgbWV6Y2xhcyBjb24gbG9zIHphcGF0b3MgbyBsb3MgcGFudGFsb25lcyDCv25vPyBMYXMgZXN0cnVjdHVyYXMgZGUgZGF0b3MgZW4gbGEgcHJvZ3JhbWFjacOzbiB0ZSBzaXJ2ZW4gcGFyYSBhY29tb2RhciBsb3MgZGF0b3MgZGUgY2llcnRhIGZvcm1hLg==","TG9zIHRpcG9zIGRlIGVzdHJ1Y3R1cmFzIGRlIGRhdG9zIHF1ZSBzZSB1c2FuIGVuIGxhIHByb2dyYW1hY2nDs24gdGFtYmnDqW4gc29uIHNpbWlsYXJlcyBhIGxvcyBxdWUgZW5jdWVudHJhcyBlbiB0dSBkw61hIGEgZMOtYS4gUG9yIGVqZW1wbG8sIGxhcyBjYW1pc2V0YXMgZGUgdHUgYXJtYXJpbyBwcm9iYWJsZW1lbnRlIGVzdMOpbiB1bmEgZW5jaW1hIGRlIGxhIG90cmEgeSBtdWNoYXMgdmVjZXMgKGFsIG1lbm9zIGxvcyBob21icmVzIHNvbGVtb3MgaGFjZXIgZXNvKSBjb2dlcyBsYSBjYW1pc2V0YSBxdWUgZXN0w6EgYXJyaWJhIGRlbCB0b2RvIHBvcnF1ZSBlcyBsYSBtw6FzIGbDoWNpbCBkZSByZXRpcmFyIHkgcG9ycXVlIG5vIHF1aWVyZXMgcHJlb2N1cGFydGUgY29uIGFxdWVsbG8gZGUgInF1w6kgbWUgcG9uZ28gaG95Ii4gRnVlcmEgZGUgYnJvbWFzLCBlc3RydWN0dXJhcyBkZSBkYXRvcyBlbmN1ZW50cmFzIGVuIGxhIHBpbGEgZGUgbGF2YXIgbG9zIHBsYXRvcywgZW4gbGEgY29sYSBkZSBsb3MgaW5ncmVzb3MgZGVsIGNpbmUsIGVuIGxhIGZpbGEgcGFyYSBzdWJpciBhbCBhdXRvYsO6cywgZXRjLiBBaG9yYSBzb2xvIGZhbHRhIHZlcmxhcyBlbiB0w6lybWlub3MgZGUgcHJvZ3JhbWFjacOzbi4=","QWRlbcOhcywgZW4gY2FkYSBsZW5ndWFqZSBkZSBwcm9ncmFtYWNpw7NuIHBvZGVtb3MgdXNhciBkaWZlcmVudGVzIGVzdHJ1Y3R1cmFzIGRlIGRhdG9zIHkgZGlmZXJlbnRlcyBpbXBsZW1lbnRhY2lvbmVzIGRlIGxhcyBtw6FzIGLDoXNpY2FzLCBjb21vIGxhcyBsaXN0YXMsIGNvbGFzLCBwaWxhcywgcXVlIHN1ZWxlbiBlc3RhciBwcmVzZW50ZXMgZW4gbGEgbWF5b3LDrWEgZGUgbG9zIGxlbmd1YWplcy4gU2kgZW50ZW5kZW1vcyBlbCBjb25jZXB0bywgaW1wb3J0YSBwb2NvIGxhIHNpbnRheGlzLCBwb3JxdWUgbGEgcG9kcmVtb3MgcmVhbGl6YXIgbm9zb3Ryb3MgbWlzbW9zIGVuIHTDqXJtaW5vcyBkZSBjw7NkaWdvIG8gbGEgZW5jb250cmFyZW1vcyBlbiBkaXZlcnNhcyBmdWVudGVzIGNvbW8gbGlicm9zIG8gdHV0b3JpYWxlcy4="];
var words3G=["wr9RVUUgRVMgTElERVI/","RWwgbMOtZGVyIGVzIGFxdWVsbGEgcGVyc29uYSBxdWUgZXMgY2FwYXogZGUgaW5mbHVpciBlbiBsb3MgZGVtw6Fz","VW5hIHBlcnNvbmEgcHVlZGUgc2VyIGVsIGplZmUgZGUgdW4gZ3J1cG8geSBubyBzZXIgdW4gbMOtZGVyIHksIGFsIGNvbnRyYXJpbywgcHVlZGUgc2VyIGVsIGzDrWRlciBzaW4gc2VyIGVsIGplZmU=","Q29uc2lndWUgYXPDrSBxdWUgbGFzIHBlcnNvbmFzIHNlIGlkZW50aWZpcXVlbiBjb24gbGFzIG1ldGFzIG1hcmNhZGFzLCBxdWUgbGFzIGhhZ2FuIHByb3BpYXMgeSBsdWNoZW4gcG9yIGVsbGFzIGNvbiB0b2RvIGVsIGVtcGXDsW8=","RGVmaW5pY2nDs24gZGUgbMOtZGVyDQpMw61kZXIsIGVzIGxhIHBlcnNvbmEgcXVlIHRyYWJhamEgY29uIHVuIGdydXBvIGUgaW5mbHV5ZSBlbiBlbCBwYXJhIGxvZ3JhIHVuIHByb3DDs3NpdG8gcXVlIHRvZG9zIGp1bnRvcyBwcmV0ZW5kZW4gYWxjYW56YXI="];
var c1=[168,362,176,428,411];
var c2=[34,323,617,409];
var c3=[14,64,111,129,142];
